/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ragnar' at '10/25/16 9:27 PM' with Gradle 3.1
 *
 * @author Ragnar, @date 10/25/16 9:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
